# Do NOT update manually; changes here will be overwritten by Copier
<<<<<<< HEAD
_commit: v1.17.2
=======
_commit: v1.14.2
>>>>>>> 579d0d31f10f82ee30050e9d6c28a865f779209c
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: false
github_enable_makepot: false
github_enable_stale_action: false
github_enforce_dev_status_compatibility: false
include_wkhtmltopdf: false
<<<<<<< HEAD
odoo_test_flavor: OCB
=======
>>>>>>> 579d0d31f10f82ee30050e9d6c28a865f779209c
odoo_version: 15.0
org_name: Odoo Community Association (OCA)
org_slug: qrtl
rebel_module_groups: []
<<<<<<< HEAD
repo_description: OCA modules for RMM
repo_name: RMM-OCA
repo_slug: rmm-oca
repo_website: ' https://www.quartile.co'
=======
repo_description: null
repo_name: null
repo_slug: rmm-oca
repo_website: ''
>>>>>>> 579d0d31f10f82ee30050e9d6c28a865f779209c
travis_apt_packages: []
travis_apt_sources: []

